name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - python-version: "3.13"
            os: ubuntu-latest
            coverage: true  # Mark only this combination for coverage to prevent error: https://sonarsource.atlassian.net/browse/SQSCANGHA-83 & https://community.sonarsource.com/t/my-first-analyses-has-failed-when-added-project-analysis-id-38152260-0ab1-4a18-846f-1f2371079b5f/134798/27
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          uv sync --locked --all-extras

      - name: Test with pytest
        run: |
          uv run pytest
