name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          python_version: ${{ matrix.python_version }}
          cache-downloads: true
          cache-env: true
          environment-file: ./environment.yml

      - name: Install test dependencies
        run: |
          pip install -e ".[tests]"
      - name: Test with pytest
        run: |
          pytest tests
