name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup MiniConda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cht_cyclones
          auto-update-conda: true
          channels: conda-forge

      - name: Create environment
        shell: bash -el {0}
        run: |
          conda create -n cht_cyclones python=${{ matrix.python-version }} -y

      - name: Install test dependencies
        run: |
          conda run -n cht_cyclones pip install -e ".[tests]"

      - name: Test with pytest
        run: |
          conda run -n cht_cyclones pytest tests

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
